---
# defaults file for nginx

<<<<<<< HEAD
- name: install PHP
  ansible.builtin.yum:
    name:
      - php
      - php-mysqlnd
      - php-gd
      - php-curl
    state: present
=======

>>>>>>> origin/feature/jenkinspipeline-stages
