// // pipeline {
// //   agent any

// //   environment {
// //       ANSIBLE_CONFIG="${WORKSPACE}/deploy/ansible.cfg"
// //     }

// //   parameters {
// //       string(name: 'inventory', defaultValue: 'dev',  description: 'This is the inventory file for the environment to deploy configuration')
// //     }

// //   stages{
// //       stage("Initial cleanup") {
// //           steps {
// //             dir("${WORKSPACE}") {
// //               deleteDir()
// //             }
// //           }
// //         }

// //       stage('Checkout SCM') {
// //          steps{
// //             git branch: 'feature/jenkinspipeline-stages', url: 'https://github.com/fareedmirzay/ansible-config.git'
// //          }
// //        }

// //       stage('Prepare Ansible For Execution') {
// //         steps {
// //           sh 'echo ${WORKSPACE}' 
// //           sh 'sed -i "3 a roles_path=${WORKSPACE}/roles" ${WORKSPACE}/deploy/ansible.cfg'  
// //         }
// //      }

// //       stage('Run Ansible playbook') {
// //         steps {
// //            ansiblePlaybook become: true, colorized: true, credentialsId: 'private-key', disableHostKeyChecking: true, installation: 'ansible', inventory: '/etc/ansible/hosts', playbook: 'playbooks/site.yml'
// //          }
// //       }

// //       stage('Clean Workspace after build'){
// //         steps{
// //           cleanWs(cleanWhenAborted: true, cleanWhenFailure: true, cleanWhenNotBuilt: true, cleanWhenUnstable: true, deleteDirs: true)
// //         }
// //       }
// //    }

// // }

// pipeline {
//   agent any

//   environment {
//       ANSIBLE_CONFIG="${WORKSPACE}/deploy/ansible.cfg"
//     }

//   parameters {
//       string(name: 'inventory', defaultValue: 'dev',  description: 'This is the inventory file for the environment to deploy configuration')
//     }

//   stages{
//       stage("Initial cleanup") {
//           steps {
//             dir("${WORKSPACE}") {
//               deleteDir()
//             }
//           }
//         }

//       stage('Checkout SCM') {
//          steps{
//             git branch: 'feature/jenkinspipeline-stages', url: 'https://github.com/fareedmirzay/ansible-config.git'
//          }
//        }

//       stage('Prepare Ansible For Execution') {
//         steps {
//           sh 'echo ${WORKSPACE}' 
//           sh 'sed -i "3 a roles_path=${WORKSPACE}/roles" ${WORKSPACE}/deploy/ansible.cfg'  
//         }
//      }

//       stage('Run Ansible playbook') {
//         steps {
//            ansiblePlaybook become: true, colorized: true, credentialsId: 'private-key', disableHostKeyChecking: true, installation: 'ansible', inventory: '/etc/ansible/hosts', playbook: 'playbooks/site.yml'
//          }
//       }

//       stage('Clean Workspace after build'){
//         steps{
//           cleanWs(cleanWhenAborted: true, cleanWhenFailure: true, cleanWhenNotBuilt: true, cleanWhenUnstable: true, deleteDirs: true)
//         }
//       }
//    }

// }


pipeline {
    agent any  // Use any available agent

    stages {
        stage('Checkout') {
            steps {
                // Checkout the source code from the repository
                git url: 'https://github.com/fareedmirzay/ansible-config.git', branch: 'feature/jenkinspipeline-stages'
            }
        }
        
        stage('Build') {
            steps {
              script {
                sh 'echo "Building Stage"'
              }
            }
        }
        
        stage('Test') {
            steps {
              script {
                sh 'echo "Testing Stage"'
              }
                
            }
        }
    }
    post {
        success {
            echo 'Build and tests succeeded!'
        }
        failure {
            echo 'Build or tests failed.'
        }
        always {
            // Steps that are always run regardless of success or failure
            echo 'Cleaning up...'
        }
    }
}
